### ISSUE TITLE
add wasm bindings

### ISSUE THREAD

**Issue by ncitron** [a16z/helios#76]
We may need to experiment with removing references to the filesystem in the checkpoint saving logic to make this work. It also looks like ethers-rs is not properly compiling to wasm at the moment. BLST may need some messing around with. Overall its a decent sized endeavor, but will really help deliver on the portability front.

The ethers-rs issue is tracked at https://github.com/gakonst/ethers-rs/issues/1824

**Comment by banky** [comment]
I'm currently trying to integrate helios into a dapp, so I'll be taking a look at the wasm bindings

**Comment by ncitron** [comment]
I've been working on the bindings in [this branch](https://github.com/a16z/helios/tree/wasm-support). I'm curious to learn how you would consume the wasm bindings. Are there any features you are looking for?

**Comment by banky** [comment]
I'd like to build a hardhat plugin to allow developers to build web dapps on top of helios instead of relying on a third party RPC. I think this will be great for making defi apps more permissionless

@ncitron btw, are you able to compile this branch? I'm seeing some errors, and I'm not sure if it's my environment. I can help to push this across the finish line, granted I am very new to rust so might take a bit of time

**Comment by ncitron** [comment]
The branch is currently using a patched version of `ssz-rs` which is linking to a local one on my machine. Working on getting a fix for ssz-rs merged soon.

**Comment by banky** [comment]
Okay thank you, please ping if you're able to get that working

**Comment by banky** [comment]
btw, out of curiosity @ncitron, why use ssz instead of lighthouse?

**Comment by ncitron** [comment]
I looked at both. I found ssz-rs to be easier to use

**Comment by ncitron** [comment]
@banky the current build should be working everywhere now. Only the helios-ts package will build, as I definitely bricked the main helios package in the process. If you want to checkout the branch and give it a try, I added a [readme](https://github.com/a16z/helios/blob/wasm-support/helios-ts/README.md).

It is currently very limited, but it can follow the chain, and supports a couple of simple functions such as `getBalance`, `getBlockNumber`, and `getCode`, but it's a start.

**Comment by banky** [comment]
Thanks! I'll try it out this week

**Comment by iteyelmp** [comment]
hello, I used ‘ethers = { git = "https://github.com/ncitron/ethers-rs", branch = "fix-retry" }’ to compile, but the compilation failed. What is the reason?

<img width="670" alt="WeChatcbdb2e1aa50a76dbea92d244e70a9a14" src="https://user-images.githubusercontent.com/6647261/203289068-a602b6ca-85a3-41e5-b432-fca0b18062b1.png">

![63581669111217_ pic](https://user-images.githubusercontent.com/6647261/203288848-e3b172e4-a61d-4ffe-9639-368682a71d58.jpg)

**Comment by ncitron** [comment]
@iteyelmp my bad, it should work now

**Comment by iteyelmp** [comment]
Thanks, the code compiled and passed

**Comment by iteyelmp** [comment]
Because I am not very familiar with rust, can I take the compiled bundle.js and 9b508e72e7d9970a2273.module.wasm file and put it in other web projects?

**Comment by iteyelmp** [comment]
<img width="539" alt="image" src="https://user-images.githubusercontent.com/6647261/203532805-25bdbb3f-ec41-40ba-8e86-c3a84c206fc0.png"><img width="569" alt="image" src="https://user-images.githubusercontent.com/6647261/203532634-b679a168-567f-42a3-ba91-53785e82f9c3.png">

**Comment by banky** [comment]
@ncitron, I'm still getting a bunch of build errors unfortunately after following your README instructions. eg. 

```
error[E0432]: unresolved import `crate::sys::IoSourceState`
  --> /Users/banky/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.8.5/src/io_source.rs:12:5
   |
12 | use crate::sys::IoSourceState;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `IoSourceState` in `sys`

error[E0432]: unresolved import `crate::sys::tcp`
  --> /Users/banky/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.8.5/src/net/tcp/listener.rs:15:17
   |
15 | use crate::sys::tcp::{bind, listen, new_for_addr};
   |                 ^^^ could not find `tcp` in `sys`

error[E0432]: unresolved import `crate::sys::tcp`
  --> /Users/banky/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.8.5/src/net/tcp/stream.rs:13:17
   |
13 | use crate::sys::tcp::{connect, new_for_addr};
   |                 ^^^ could not find `tcp` in `sys`

error[E0433]: failed to resolve: could not find `Selector` in `sys`
   --> /Users/banky/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.8.5/src/poll.rs:301:18
    |
301 |             sys::Selector::new().map(|selector| Poll {
    |                  ^^^^^^^^ could not find `Selector` in `sys`
```

**Comment by banky** [comment]
Hey @ncitron, I'm having some compilation issues related to type mismatches that look like this. Do you know what might be causing this? 

```
error[E0308]: mismatched types
   --> execution/src/evm.rs:258:13
    |
257 |         Ok(Some(AccountInfo::new(
    |                 ---------------- arguments to this function are incorrect
258 |             account.balance,
    |             ^^^^^^^^^^^^^^^ expected struct `primitive_types::U256`, found struct `ethers::types::U256`
    |
    = note: struct `ethers::types::U256` and struct `primitive_types::U256` have similar names, but are actually distinct types
```

**Comment by ncitron** [comment]
@banky for some reason I had to delete the target directory and fully rebuild. Think it has something to do with cargo not properly handling the version updates. If that doesn't work trying deleted the cargo.lock file and rebuilding from scratch.

The final version will just be an npm package so nobody will need to deal with these build issues

**Comment by banky** [comment]
Damn, sadly that didn't work. Not sure what's going on but I'll do some more digging

**Comment by aewc** [comment]
we should using updated ssz-rs, as the fixed the overflow on 32 bit architectures:
https://github.com/ralexstokes/ssz-rs/commit/7aca2cc53dfb1c180465bf6c3f663cb85daf2fc7

**Comment by ufoscout** [comment]
Am I wrong or the scope of this issue is not "wasm" but more specifically "wasm in the browser/nodejs"?

For a project of my company, we are interested in having helios running in wasm runtimes like wasmtime or wasmer; however, among other restrictions, these environments do not have a JS runtime and cannot perform HTTP calls through `reqwest`.

To be very "wasm32" friendly, there are at least two code portions that should be reworked:
1. How HTTP calls are performed
2. How the filesystem is accessed

Both problems could be resolved by isolating the HTTP and FS calls behind an abstraction layer, e.g. something like:
```rust
trait NetworkClient {
   fn get(...) -> ...
   ...
}

trait DataClient {
   fn read(...) -> ...
   ...
}
```

and then provide default implementations of those clients (i.e. with `reqwest` and filesystem) that can be disabled using cargo features.

If there is interest in this approach, my team could perform some explorative work in this direction.

**Comment by ncitron** [comment]
Yeah this makes sense @ufoscout. Do you have a telegram I can reach you at? Would love to get into some details on how we can make the wasm feature support your use case?

Feel free to reach me on tg @ ncitron.

**Comment by ncitron** [comment]
closed by #182
